const constants = {
    ADD_BOOK: "ADD_BOOK",
    DELETE_BOOK: "DELETE_BOOK",
    SET_GOAL: "SET_GOAL",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_BOOK_TITLES: "FETCH_BOOK_TITLES",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
}
export default constants;